### ISSUE TITLE
Not able to run fp8_gemm_rowwise

### ISSUE THREAD

**Issue by karthik-man** [pytorch-labs/tritonbench#71] opened 2024-11-22 03:00 UTC
I am running into 

(my-pt) [kmanivannan@devgpu007.rva6 ~/tritonbench (main)]$ python run.py --op fp8_gemm_rowwise --m 16384 --n 16384 --k 16384
Traceback (most recent call last):
  File "/home/kmanivannan/tritonbench/run.py", line 16, in <module>
    from tritonbench.operator_loader import load_opbench_by_name_from_loader
  File "/home/kmanivannan/tritonbench/tritonbench/operator_loader/__init__.py", line 8, in <module>
    from torch._inductor.compile_fx import compile_fx
  File "/home/kmanivannan/pytorch/torch/_inductor/compile_fx.py", line 50, in <module>
    from torch._inductor.debug import save_args_for_compile_fx_inner
  File "/home/kmanivannan/pytorch/torch/_inductor/debug.py", line 26, in <module>
    from . import config, ir  # noqa: F811, this is needed
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmanivannan/pytorch/torch/_inductor/ir.py", line 77, in <module>
    from .runtime.hints import ReductionHint
  File "/home/kmanivannan/pytorch/torch/_inductor/runtime/hints.py", line 36, in <module>
    attr_desc_fields = {f.name for f in fields(AttrsDescriptor)}
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kmanivannan/.conda/envs/my-pt/lib/python3.11/dataclasses.py", line 1246, in fields
    raise TypeError('must be called with a dataclass type or instance') from None

Is this a setup issue?

**Comment by adamomainz** [comment] 2024-11-22 03:28
looks like an issue with your pytorch version w.r.t compatibility here somehow. are you using the nightly pytorch or which version? I tried to reproduce but didnt get your error

<img width="1336" alt="Screenshot 2024-11-21 at 9 27 57 PM" src="https://github.com/user-attachments/assets/8ff4b260-0a69-494b-aad8-b1fd2465b149">

**Comment by ChandlerGuan** [comment] 2024-11-22 05:23
```
Traceback (most recent call last):
  File "/home/yue/triton_benchmark/run.py", line 16, in <module>
    from tritonbench.operator_loader import load_opbench_by_name_from_loader
  File "/home/yue/triton_benchmark/tritonbench/operator_loader/__init__.py", line 7, in <module>
    from torch._dynamo.backends.cudagraphs import cudagraphs_inner
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/backends/cudagraphs.py", line 10, in <module>
    from torch._inductor.cudagraph_trees import cudagraphify_impl
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 71, in <module>
    from torch._inductor.compile_fx import (
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 40, in <module>
    from torch._inductor.codecache import code_hash, CompiledFxGraph, FxGraphCache
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 48, in <module>
    from torch._inductor import config, exc, metrics
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/metrics.py", line 13, in <module>
    from torch._inductor.utils import get_benchmark_name
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/utils.py", line 696, in <module>
    attr_desc_fields = {f.name for f in fields(AttrsDescriptor)}
  File "/opt/conda/lib/python3.10/dataclasses.py", line 1198, in fields
    raise TypeError('must be called with a dataclass type or instance') from None
TypeError: must be called with a dataclass type or instance
```

Same here with `torch 2.3.0`

**Comment by adamomainz** [comment] 2024-11-22 13:02
strange ok let me look further today!

**Comment by xuzhao9** [comment] 2024-11-22 14:15
@FindHao compile_fx is not being used by regular operators, can we delay import of this package?

**Comment by FindHao** [comment] 2024-11-22 17:25
> @FindHao compile_fx is not being used by regular operators, can we delay import of this package?

import compile_fx is not supposed to have issues. delaying it may not be the best solution.

@karthik-man can you share your pytorch version?

**Comment by adamomainz** [comment] 2024-11-22 17:27
> > @FindHao compile_fx is not being used by regular operators, can we delay import of this package?
> 
> import compile_fx is not supposed to have issues. delaying it may not be the best solution.
> 
> @karthik-man can you share your pytorch version?

@FindHao  version was torch 2.3.0. I dont think there should be a problem delaying the import I put up a diff for it and is landed https://github.com/pytorch-labs/tritonbench/commit/17e025dd99fc3b7417cbc89cfe4208928a44fb50?fbclid=IwZXh0bgNhZW0CMTEAAR21kLR4nVnEeMDBm_7FL47797vuehmHu7on1xYFyDnWG5CLjJLfj-RRpfk_aem_cQANdYzqy57PmhCbx9MN8Q

**Comment by FindHao** [comment] 2024-11-22 17:29
> > > @FindHao compile_fx is not being used by regular operators, can we delay import of this package?
> > 
> > 
> > import compile_fx is not supposed to have issues. delaying it may not be the best solution.
> > @karthik-man can you share your pytorch version?
> 
> @FindHao version was torch 2.3.0. I dont think there should be a problem delaying the import I put up a diff for it and is landed [17e025d?fbclid=IwZXh0bgNhZW0CMTEAAR21kLR4nVnEeMDBm_7FL47797vuehmHu7on1xYFyDnWG5CLjJLfj-RRpfk_aem_cQANdYzqy57PmhCbx9MN8Q](https://github.com/pytorch-labs/tritonbench/commit/17e025dd99fc3b7417cbc89cfe4208928a44fb50?fbclid=IwZXh0bgNhZW0CMTEAAR21kLR4nVnEeMDBm_7FL47797vuehmHu7on1xYFyDnWG5CLjJLfj-RRpfk_aem_cQANdYzqy57PmhCbx9MN8Q)

The previous log shows two different errors. one is `compile_fx`, and one is `cudagraphs_inner`.

**Comment by adamomainz** [comment] 2024-11-22 17:38
@FindHao  diff D66372865 and pr https://github.com/pytorch-labs/tritonbench/pull/73

**Comment by FindHao** [comment] 2024-11-22 17:50
I tested torch 2.3.0 locally. can't reproduce this issue. This can be a hidden boom. Let's keep an eye on it.

**Comment by karthik-man** [comment] 2024-11-22 20:59
I upgraded my pytorch and I no longer hit this error.

**Comment by adamomainz** [comment] 2024-11-22 21:01
@karthik-man  glad to hear. closing issue

**Closed by adamomainz** 2024-11-22 21:01 UTC
